dist: xenial
git:
  depth: 1
before_install:
- openssl aes-256-cbc -K $encrypted_973234595f6e_key -iv $encrypted_973234595f6e_iv
  -in travis_key.enc -out travis_key -d
- sudo apt-get -qq update
- sudo apt-get install -y fakeroot fakechroot
script:
- cd $TRAVIS_BUILD_DIR
- git checkout travis
- bash ./travisUpdateThis.sh
