dist: xenial
git:
  depth: 1
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y fakeroot fakechroot
script:
  - cd $TRAVIS_BUILD_DIR
  - git checkout travis
  # - openssl aes-256-cbc -K $encrypted_fd4d87192dd3_key -iv $encrypted_fd4d87192dd3_iv -in travis_key.enc -out travis_key -d
  - bash ./updateThis.sh
