#!/usr/bin/env bash
set -e -u -o pipefail

cd $TRAVIS_BUILD_DIR

./build_root_targz.sh |& tee thisBuild.log

git config user.name "Travis CI"
git config user.email "travis@rob.ot"

git add thisBuild.log
git add archlinux.tar.xz
git add Dockerfile

chmod 600 travis_key
eval `ssh-agent -s`

ssh-add travis_key
rm travis_key

git commit -m "$(date -u -I): bump to latest Arch Linux -- via travis"

export GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

git remote set-url --push origin git@github.com:greyltc/docker-archlinux.git

TAG="$(date -u -I)"
git tag --annotate --force --message="${TAG} generated by travis" "${TAG}" master
git push origin master --force --tags

# now let's make the github package
echo "$GITHUB_TOKEN" | docker login docker.pkg.github.com --username greyltc --password-stdin
docker build -t archlinux .
IMAGE_ID=$(docker images archlinux --format "{{.ID}}")
docker tag $IMAGE_ID docker.pkg.github.com/greyltc/docker-archlinux/archlinux:$(date -I)
docker push docker.pkg.github.com/greyltc/docker-archlinux/archlinux:$(date -I)
